import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const { width, height } = Dimensions.get("screen");
// -------- valores importantes --------------- //
const valores = {
  fotosEsquina: {
    anchoFoto: width * 0.5, // ancho de las fotos de las esquinas
    altoFoto: width * 0.5 * 0.77, // alto de las fotos de las esquinas
    top: height * 0.18, //top de las fotos de las esquinas
    bottom: height * 0.06, //bottom de las fotos de las esquinas
  },
  fotosMedio: {
    anchoFotoMedio: width * 0.35, // ancho de las 2 fotos interiores
    altoFotoMedio: height * 0.1
  },
  valoresGenerales: {
    borde: "rgb(230, 230, 230)", // color del borde de las fotos
    curvatura: 10, // border radius de las fotos
    resizeMode: "cover",
  },
};

export const styles = StyleSheet.create({
  containerPadre: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    position: "relative",
  },
  header: {
    width: "100%",
    height: "10%",
    backgroundColor: "grey",
    display: "flex",
    marginTop: 30,
    alignItems: "center",
  },
  medio: {
    width: "100%",
    height: 72,
    backgroundColor: "white",
    position: "absolute",
    top: "47%",
    borderWidth: 2,
    borderColor: "white",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  container1: {
    width: valores.fotosEsquina.anchoFoto,
    height: valores.fotosEsquina.altoFoto,
    backgroundColor: "white",
    position: "absolute",
    top: valores.fotosEsquina.top,
    right: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 2,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  container2: {
    width: valores.fotosEsquina.anchoFoto,
    height: valores.fotosEsquina.altoFoto,
    backgroundColor: "white",
    position: "absolute",
    top: valores.fotosEsquina.top,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 2,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  container3: {
    width: valores.fotosMedio.anchoFotoMedio,
    height: valores.fotosMedio.altoFotoMedio,
    position: "absolute",
    backgroundColor: "white",
    top: height * 0.22,
    right: width * 0.33,
    zIndex: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 2,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  container4: {
    width: valores.fotosMedio.anchoFotoMedio,
    height: valores.fotosMedio.altoFotoMedio,
    position: "absolute",
    bottom: height * 0.2,
    right: width * 0.33,
    zIndex: 100,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 2,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  container5: {
    width: valores.fotosEsquina.anchoFoto,
    height: valores.fotosEsquina.altoFoto,
    position: "absolute",
    bottom: valores.fotosEsquina.bottom,
    right: 0,
    marginBottom: 80,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 2,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  container6: {
    width: valores.fotosEsquina.anchoFoto,
    height: valores.fotosEsquina.altoFoto,
    position: "absolute",
    bottom: valores.fotosEsquina.bottom,
    marginBottom: 80,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: valores.valoresGenerales.curvatura,
    borderWidth: 1,
    borderColor: valores.valoresGenerales.borde,
    resizeMode: valores.valoresGenerales.resizeMode,
  },
  footer: {
    width: "100%",
    height: 78,
    position: "absolute",
    bottom: 0,
    backgroundColor: "grey",
  },
  logoIvan: {
    width: 210,
    position: "absolute",
    bottom: 20,
    left: -15,
    resizeMode: "contain",
  },
  cologo: {
    width: 60,
    resizeMode: "contain",
    position: "absolute",
    right: 20,
    bottom: -7,
  },
  images: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 10,
  },
  estiloView: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    top: "42%",
    left: "31%",
    zIndex: 1000,
    width: 150,
    height: 30,
    backgroundColor: "grey",
  },
  estiloTexto: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
});
