import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  containerPadre: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    position: "relative",
    //display: "flex"
  },
  header: {
    width: "100%",
    height: 50,
    backgroundColor: "grey",
    display: "flex",
    marginTop: 30,
    alignItems: "center",
  },
  medio: {
    width: "100%",
    height: 72,
    backgroundColor: "white",
    position: "absolute",
    top: "45%",
    borderWidth: 2,
    borderColor: "black",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  container1: {
    width: "40%",
    height: "26%",
    backgroundColor: "white",
    position: "absolute",
    top: 80,
    right: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  container2: {
    width: "40%",
    height: "26%",
    backgroundColor: "white",
    position: "absolute",
    top: 80,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  container3: {
    width: "40%",
    height: "26%",
    position: "absolute",
    backgroundColor: "white",
    top: "18%",
    right: "30%",
    zIndex: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  container4: {
    width: "40%",
    height: "26%",
    position: "absolute",
    bottom: "18%",
    left: "30%",
    zIndex: 100,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  container5: {
    width: "40%",
    height: "26%",
    position: "absolute",
    bottom: 0,
    right: 0,
    marginBottom: 80,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  container6: {
    width: "40%",
    height: "26%",
    position: "absolute",
    bottom: 0,
    marginBottom: 80,
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    resizeMode: "cover",
  },
  footer: {
    width: "100%",
    height: 78,
    position: "absolute",
    bottom: 0,
    backgroundColor: "grey",
  },
  logoIvan: {
    width: 210,
    position: "absolute",
    bottom: 20,
    left: -15,
    resizeMode: "contain",
  },
  cologo: {
    width: 60,
    resizeMode: "contain",
    position: "absolute",
    right: 20,
    bottom: -7,
  },
  images: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
});
